version: '3.9'
services:
  equipe-app:
    container_name: equipe-app-name
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongo_container
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:example
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
  
  redis:
    image: redis
    container_name: redis_container